# -*- coding: utf-8 -*-
"""aresty_data_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qaL0RFnU3Kvm9KlKo_AGdPNnaJCCjocs
"""

# Requied libraries/packages
# ==========================
require(MASS)
install.packages("devtools")
library(devtools)
library(ggplot2)

main_data <- read.csv(file="/content/stacked-data-ergodicity.csv",header = TRUE)
summary(main_data)

# Regression
# ==========
lmod <- lm(choice ~ Xa+Xb+H+D+T , data=main_data)           # linear model regression
summary(lmod)

anova(lmod)

coef(lmod)

confint(lmod)             # CI at 95%
confint(lmod, level=.99)  # CI at 99%

plot(lmod)

lmod_g <- glm(choice ~ Xa+Xb+H+D+T , data=main_data)        # generalized linear model
summary(lmod_g)

anova(lmod_g)

confint(lmod_g)             # CI at 95%
confint(lmod_g, level=.99)  # CI at 99%

lmod_gnb <- glm.nb(choice ~ Xa+Xb+H+D+T , data=main_data)   # negative binomial model

summary(lmod_gnb)

anova(lmod_gnb)

confint(lmod_gnb)             # CI at 95%
confint(lmod_gnb, level=.99)  # CI at 99%

