library(faraway)
library(caret)
library(olsrr)
require(caret)
covid19 <- read.csv(file="C:/Users/riven/Desktop/stat486 hw/Final Project.csv",header = TRUE)
head(covid19 )


#model generated by forward
model1 <- lm(P_diagnosed ~ P_resident + P_Density + Q3GDP + P_Homeless,data = covid19)

#model generated by backward and stepwise
model2 <- lm(P_diagnosed ~ P_resident + P_Density + P_Homeless,data = covid19)

#CV for model1
set.seed(32145)
train.control <- trainControl(method = "cv", number = 5)
model_forward <- train(P_diagnosed ~ P_resident + P_Density + Q3GDP + P_Homeless,data = covid19, method = "lm", trControl = train.control)
# Summarize the results
print(model_forward)

#CV for model2
set.seed(12345)
train.control <- trainControl(method = "cv", number = 5)
model_backward <- train(P_diagnosed ~ P_resident + P_Density + P_Homeless,data = covid19, method = "lm", trControl = train.control)
# Summarize the results
print(model_backward)






